### ISSUE TITLE
Should add this nice library to quicklisp

### ISSUE THREAD

**Issue by anquegi** [jkcunningham/faker#1]
Hi I think, that these nice project should be added to quicklisp. This is not really an issue, i shout be an advice
it works well with (ql:quickload :faker) and would be nice to work with it only writing that line, instead of clonig the repo in local-projects and load from  that directory.

Thanks!

**Comment by jkcunningham** [comment]
I have no objection, but so far as I know that would be up to Zach. 
CMIIW.
